---

- name: playbook 1
  hosts: localhost
  connection: local 
  gather_facts: True

  tasks:

  - name: print Hello Ansible
    ansible.builtin.debug:
      msg: "Hello from Ansible Playbook 1"

  - name: print facts 
    ansible.builtin.debug:
      msg: "{{ item }}"
    #with_items:
    loop:
      - "ansible_hostname: {{ ansible_hostname }}"
      - "ansible_distribution: {{ ansible_distribution }}" 
      - "ansible_distribution_release: {{ ansible_distribution_release }}" 
      - "ansible_distribution_version: {{ ansible_distribution_version }}"
      #- "ansible_default_ipv4.address: {{ ansible_default_ipv4.address }}" # su container GH non definito

