name: CI/CD workflow with pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt

      - name: Run tests
        run: |
          pytest -v python/unit-test/pytest_math_functions.py

      - name: Create artifact with math_functions.py
        uses: actions/upload-artifact@v2
        with:
          name: math-functions-artifact
          path: python/unit-test/math_functions.py

      ## ToDo: KO
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: ./coverage/html/index.html
      

  deploy:
    runs-on: vps-ubuntu-ovh  # This job runs on your self-hosted runner
    environment: My_Environment_1
    needs: build_and_test  # This job waits for build_and_test to finish

    steps:

      - name: Download artifacts from previous job
        uses: actions/download-artifact@v2
        with:
          name: math-functions-artifact  # Name of the artifact uploaded in build_and_test job (optional)


      - name: Copy script to target location
        run: |
          sshpass -p ${{ secrets.PASSWORD_SELF_HOSTED_RUNNER }} scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT_VPS }} python/unit-test/pytest_math_functions.py ${{ secrets.USERNAME_SELF_HOSTED_RUNNER }}@${{ secrets.IP_SELF_HOSTED_RUNNER }}:/tmp/ 


      - name: Copia artifact su host remoto con SCP
        run: |
          sshpass -p ${{ secrets.PASSWORD_SELF_HOSTED_RUNNER }} scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT_VPS }} /home/vimi/github/actions-runner/vitmil-gh-actions-demo/_work/gh-actions-demo/gh-actions-demo/math_functions.py ${{ secrets.USERNAME_SELF_HOSTED_RUNNER }}@${{ secrets.IP_SELF_HOSTED_RUNNER }}:/tmp/ABC.py

      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_SELF_HOSTED_RUNNER }}
          port: ${{ secrets.SSH_PORT_VPS }}
          username: ${{ secrets.USERNAME_SELF_HOSTED_RUNNER }}
          password: ${{ secrets.PASSWORD_SELF_HOSTED_RUNNER }}
          #key: ${{ secrets.SSH_KEY }}  # Replace with your SSH private key (encrypted in secrets)
          script: | 
            whoami
            hostname
