name: access to secrets and vars

on:
  push:
    branches: [ main ]

jobs:

  access_to_secrets_and_vars:
    runs-on: ubuntu-latest
    #runs-on: vps-ubuntu-ovh    
    # per accedere alle variabili e secrets dentro il mio Environment creato nel repository
    environment: My_Environment_1

    steps:
    - uses: actions/checkout@v3

    - name: Accedo ai secrets e variabili del Environment del repo 
      run: |
        echo "Il valore della mia variabile d'ambiente è ${{ vars.MY_VAR_1 }}"
        echo "Il valore del mio segreto è ${{ secrets.MY_SECRET_1 }}"


  create_wf_var_at_runtime:
    runs-on: ubuntu-latest
    #runs-on: vps-ubuntu-ovh
    environment: My_Environment_1
    # setto ulteriori variabili dentro l'env di esecuzione del workflow
    env:
      VAR_FROM_WORKFLOW : "Hello from var of workflow"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Run script get_vars_from_gh_env.py
      run: python python/get_vars_from_gh_env.py "$VAR_FROM_WORKFLOW"
      