##############################################
## Container ansible dentro immagine Ubuntu ##
##############################################
## All’interno della macchina virtuale, puoi scegliere di eseguire i tuoi jobs all’interno di un container Docker,
## utilizzando il campo container nel file di workflow. 
## In questo caso, tutti i passaggi del job che non specificano già un container verranno eseguiti all’interno del container Docker.
##
## NOTE: ansible non è installato nel container.
## Va installato:
## apt update && apt install ansible
## 
## TODO ERROR
##  The default action is to keep your current version.
## *** hosts (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package ansible (--configure):
##  EOF on stdin at conffile prompt
## Errors were encountered while processing:
##  ansible
## E: Sub-process /usr/bin/dpkg returned an error code (1)
name: ansible on container ansible

on: [push]

jobs:
  job_1:
    if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job (vedi errori sopra)
    runs-on: ubuntu-latest
    container:
      image: ansible/ansible:ubuntu1404

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Run Ansible playbook
      #   run: ansible-playbook ansible/playbook_1.yaml

      - name: execute hostname
        run: hostname

      - name: install ansible 
        run: |
          apt -y update
          apt -y install ansible

      - name: Run playbook_1
        run: |
          ansible-playbook ansible/playbook_1.yaml
