name: docker on self-hosted runner

on: [push]

jobs:
  container-test-job:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job 
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh
    container:
      image: almalinux:latest
      env:
        NODE_ENV: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: print hostname by bash command
      run: hostname