name: python execute code on self-hosted runner

on:
  push:
    branches: [ main ]

jobs:
  job_1:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh

    steps:

    - uses: actions/checkout@v3

    - name: install python if not present
      run: |
        if ! which python3 > /dev/null 2>&1 ; then 
          sudo apt update -y
          sudo apt install  python3 -y
        fi

    - name: print hostname by python script (on container)
      run: |
        python3 -c """
        import socket  
        print(socket.gethostname())
        """

    - name: print current user 
      run: id
