name: python execute code on self-hosted runner

on:
  push:
    branches: [ main ]

jobs:

  job_1:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh

    steps:

    - uses: actions/checkout@v3

    - name: install python if not present
      run: |
        pkg_mngr=""
        if ! which python3 > /dev/null 2>&1 ; then 
          echo -e "[INFO]: install python3...\n"
          if which apt ; then 
            pkg_mngr="apt"
          elif which dnf ; then 
            pkg_mngr="dnf"
          else 
            pkg_mngr="yum"
          fi
        sudo $pkg_mngr update -y
        sudo $pkg_mngr install python3 -y
        else
          echo -e "\n[INFO]: python3 already installed"
        fi    

    - name: execute hardcoded python script
      run: |
        python3 -c """
        import socket  
        print(socket.gethostname())
        """
    
    - name: Run script from repo
      run: |
        export PYTHON=""
        if which python ; then 
          export PYTHON="python"
        else
          export PYTHON="python3"
        fi 
        $PYTHON python/request_ident_me.py

    - name: test 
      run: echo $PYTHON

    - name: print current user 
      run: id
