name: ssh actions

on:
  push:
    branches: [ main ]

jobs:
  job_1:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh
    # per accedere alle variabili e secrets dentro il mio Environment creato nel repository
    environment:  My_Environment_1

    steps:
    - uses: actions/checkout@v3

    # - name: access to secrets 
    #   run: |
    #     echo ${{ secrets.IP_SELF_HOSTED_RUNNER }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_SELF_HOSTED_RUNNER }}
        username: ${{ secrets.USERNAME_SELF_HOSTED_RUNNER }}
        password: ${{ secrets.PASSWORD_SELF_HOSTED_RUNNER }}
        #port: ${{ secrets.PORT }}
        port: 2222
        script: | 
          whoami
          hostname
          sudo ls -l /home/vimi/github/actions-runner/vitmil-gh-actions-demo/_work/gh-actions-demo/gh-actions-demo/.github/workflows/
          sudo chown -R vimi:vimi 
          sudo ls -l /home/vimi/github/actions-runner/vitmil-gh-actions-demo/_work/gh-actions-demo/gh-actions-demo/.github/workflows/

