name: ssh actions

on:
  push:
    branches: [ main ]

jobs:
  job_1:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo il job
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh

    steps:
    - uses: actions/checkout@v3

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_SELF_HOSTED_RUNNER }}
        username: ${{ secrets.USERNAME_SELF_HOSTED_RUNNER }}
        password: ${{ secrets.PASSWORD_SELF_HOSTED_RUNNER }}
        #port: ${{ secrets.PORT }}
        port: 22
        script: | 
          whoami
          hostname
          ls -l _work/gh-actions-demo/gh-actions-demo/.github/workflows/

