name: Install Ansible and run playbook on gh-runner

on: [push]

jobs:

  job_1:
    #if: github.ref == 'refs/heads/no-branch-for-skip' # skippo questo workflow
    
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: print hostname
      run: hostname

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run playbook_1
      run: |
        ansible/ansible-playbook playbook_1.yaml
